blob/urls.py
from django.urls import path

from blob.views import (
    PostListView,
    PostUpdateView,
    PostDetailView,
    PostDeleteView,
    CommentaryCreateView,
    CommentaryDetailView,
    CommentaryDeleteView,
)

urlpatterns = [
    path("", PostListView.as_view(), name="post-list"),
    path("<int:pk>/", PostDetailView.as_view(), name="post-detail"),
    path("<int:pk>/update/", PostUpdateView.as_view(), name="post-update"),
    path("<int:pk>/delete/", PostDeleteView.as_view(), name="post-delete"),
    path(
        "<int:pk>/commentaries/create/",
        CommentaryCreateView.as_view(),
        name="comment-create",
    ),
    path(
        "commentaries/<int:pk>/",
        CommentaryDetailView.as_view(),
        name="commentary-detail",
    ),
    path(
        "commentaries/<int:pk>/delete/",
        CommentaryDeleteView.as_view(),
        name="commentary-delete",
    ),
]

app_name = "posts"

dishes/urls.py
from django.urls import path

from blog.views import PostCreateView
from dishes.views import (
    DishCreateView,
    DishDeleteView,
    DishDetailView,
    DishListView,
    DishTypeCreateView,
    DishTypeDeleteView,
    DishTypeDetailView,
    DishTypeListView,
    DishTypeUpdateView,
    DishUpdateView,
    IndexView,
    UpdateLikeView,
    basket_add,
    basket_remove,
)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path(
        "dishes/<int:pk>/like/",
        UpdateLikeView.as_view(),
        name="update_like_dish",
    ),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path(
        "dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"
    ),
    path(
        "dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"
    ),
    path(
        "dishes/<int:pk>/create_post/",
        PostCreateView.as_view(),
        name="post-create",
    ),
    path("types/", DishTypeListView.as_view(), name="dish_type-list"),
    path(
        "types/<int:pk>/",
        DishTypeDetailView.as_view(),
        name="dish_type-detail",
    ),
    path(
        "types/create/", DishTypeCreateView.as_view(), name="dish_type-create"
    ),
    path(
        "types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish_type-update",
    ),
    path(
        "types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish_type-delete",
    ),
    path("baskets/add/<int:dish_id>/", basket_add, name="basket-add"),
    path(
        "baskets/remove/<int:basket_id>/", basket_remove, name="basket-remove"
    ),
]

app_name = "cuisine"

online_restaurant/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from orders.views import stripe_webhook_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("dishes.urls", namespace="cuisine")),
    path("accounts/", include("allauth.urls")),
    path("users/", include("users.urls", namespace="users")),
    path("posts/", include("blog.urls", namespace="posts")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("webhook/stripe/", stripe_webhook_view, name="stripe-webhook"),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path

from orders.views import (
    CanceledTemplateView,
    OrderCreateView,
    OrderDetailView,
    OrderListView,
    SuccessTemplateView,
)

urlpatterns = [
    path("create/", OrderCreateView.as_view(), name="order-create"),
    path("", OrderListView.as_view(), name="order-list"),
    path("<int:pk>/", OrderDetailView.as_view(), name="order-detail"),
    path(
        "order-success/", SuccessTemplateView.as_view(), name="order-success"
    ),
    path(
        "order-canceled/",
        CanceledTemplateView.as_view(),
        name="order-canceled",
    ),
]

app_name = "orders"

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import (
    CustomerCreateView,
    CustomerProfileView,
    EmailVerificationView,
)

urlpatterns = [
    path("create/", CustomerCreateView.as_view(), name="user-create"),
    path(
        "login/",
        LoginView.as_view(),
        name="login",
    ),
    path(
        "profile/<int:pk>", CustomerProfileView.as_view(), name="user-profile"
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "verify/<str:email>/<uuid:code>/",
        EmailVerificationView.as_view(),
        name="email_verification",
    ),
]

app_name = "users"

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a
            href="?{% query_transform request page=page_obj.previous_page_number %}"
            class="page-link">&laquo;
        </a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>

    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
      <a
          href="?{% query_transform request page=page_obj.next_page_number %}"
          class="page-link">&raquo;
      </a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav">
  {% if user.is_authenticated %}
    <li class="user-info">User: {{ user.username }}</li>
    <li><a href="{% url 'users:user-profile' user.pk %}">Profile</a></li>
    <li><a href="{% url 'users:logout' %}">Logout</a></li>
  {% else %}
    <li><a href="{% url 'users:login' %}">Login</a></li>
    <li><a href="{% url "users:user-create" %}">Registration</a></li>
  {% endif %}
  <li><a href="{% url "cuisine:index" %}">Home</a></li>
  <li><a href="{% url "cuisine:dish-list" %}">All dishes</a></li>
  <li><a href="{% url "cuisine:dish_type-list" %}">All types of available food</a></li>
  <li><a href="{% url "posts:post-list" %}">Forum</a></li>
  <li><a href="{% url "orders:order-list" %}">Orders</a></li>
  {% if user.is_superuser %}
    <li class="admin-link"><a href="{% url 'admin:index' %}">Admin panel</a></li>
  {% endif %}
</ul>