blob/urls.py
from django.urls import path

from blob.views import (
    PostListView,
    PostUpdateView,
    PostDetailView,
    PostDeleteView,
    CommentaryCreateView,
    CommentaryDetailView,
    CommentaryDeleteView,
)

urlpatterns = [
    path("", PostListView.as_view(), name="post-list"),
    path("<int:pk>/", PostDetailView.as_view(), name="post-detail"),
    path("<int:pk>/update/", PostUpdateView.as_view(), name="post-update"),
    path("<int:pk>/delete/", PostDeleteView.as_view(), name="post-delete"),
    path(
        "<int:pk>/commentaries/create/",
        CommentaryCreateView.as_view(),
        name="comment-create",
    ),
    path(
        "commentaries/<int:pk>/",
        CommentaryDetailView.as_view(),
        name="commentary-detail",
    ),
    path(
        "commentaries/<int:pk>/delete/",
        CommentaryDeleteView.as_view(),
        name="commentary-delete",
    ),
]

app_name = "posts"

blog/urls.py
from django.urls import path

from blog.views import (
    CommentaryCreateView,
    CommentaryDeleteView,
    CommentaryDetailView,
    PostDeleteView,
    PostDetailView,
    PostListView,
    PostUpdateView,
)

urlpatterns = [
    path("", PostListView.as_view(), name="post-list"),
    path("<int:pk>/", PostDetailView.as_view(), name="post-detail"),
    path("<int:pk>/update/", PostUpdateView.as_view(), name="post-update"),
    path("<int:pk>/delete/", PostDeleteView.as_view(), name="post-delete"),
    path(
        "<int:pk>/commentaries/create/",
        CommentaryCreateView.as_view(),
        name="comment-create",
    ),
    path(
        "commentaries/<int:pk>/",
        CommentaryDetailView.as_view(),
        name="commentary-detail",
    ),
    path(
        "commentaries/<int:pk>/delete/",
        CommentaryDeleteView.as_view(),
        name="commentary-delete",
    ),
]

app_name = "posts"

online_restaurant/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from orders.views import stripe_webhook_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("dishes.urls", namespace="cuisine")),
    path("accounts/", include("allauth.urls")),
    path("users/", include("users.urls", namespace="users")),
    path("posts/", include("blog.urls", namespace="posts")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("webhook/stripe/", stripe_webhook_view, name="stripe-webhook"),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

from dishes.models import Dish


class Post(models.Model):
    RATING_CHOICES = (
        (1, "very bad"),
        (2, "bad"),
        (3, "maybe"),
        (4, "good"),
        (5, "excellent"),
    )
    description = models.TextField()
    rating = models.IntegerField(choices=RATING_CHOICES)
    created_time = models.DateTimeField(auto_now_add=True)
    dish = models.ForeignKey(
        Dish, on_delete=models.CASCADE, related_name="posts"
    )
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.SET_NULL,
        related_name="posts",
        null=True,
    )

    class Meta:
        ordering = ["dish__name"]

    def __str__(self) -> str:
        return self.description[:7]

    def get_absolute_url(self) -> str:
        return reverse("posts:post-detail", kwargs={"pk": self.pk})


class Commentary(models.Model):
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.SET_NULL,
        related_name="commentaries",
        null=True,
    )
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="commentaries"
    )
    created_time = models.DateTimeField(auto_now_add=True)
    content = models.TextField(verbose_name="comment on post")

    class Meta:
        verbose_name_plural = "commentaries"
        ordering = ["-created_time"]

    def __str__(self) -> str:
        return f"posted by {self.user}"

blog/forms.py
from django import forms

from blog.models import Post


class PostCustomizeForm(forms.ModelForm):
    RATING_CHOICES = (
        (1, "very bad"),
        (2, "bad"),
        (3, "maybe"),
        (4, "good"),
        (5, "excellent"),
    )
    rating = forms.ChoiceField(
        choices=RATING_CHOICES,
        widget=forms.RadioSelect,
        label="Rating of this dish",
    )

    class Meta:
        model = Post
        fields = ("description", "rating")

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from blog.forms import PostCustomizeForm
from blog.models import Commentary, Post
from dishes.models import Dish


class PostListView(LoginRequiredMixin, generic.ListView):
    queryset = Post.objects.select_related("dish", "user").prefetch_related(
        "commentaries__user"
    )
    paginate_by = 10


class PostCreateView(LoginRequiredMixin, generic.CreateView):
    form_class = PostCustomizeForm
    template_name = "blog/post_form.html"

    def form_valid(self, form: PostCustomizeForm) -> HttpResponseRedirect:
        form.instance.user = self.request.user
        form.instance.dish = get_object_or_404(Dish, pk=self.kwargs["pk"])
        return super().form_valid(form)


class PostDetailView(LoginRequiredMixin, generic.DetailView):
    queryset = Post.objects.select_related(
        "dish__dish_type", "user"
    ).prefetch_related("commentaries__user")


class PostUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Post
    fields = ("description", "rating")


class PostDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Post
    success_url = reverse_lazy("posts:post-list")


class CommentaryCreateView(LoginRequiredMixin, generic.CreateView):
    queryset = Commentary.objects.select_related("post__user")
    fields = ("content",)
    template_name = "blog/commentary_form.html"

    def form_valid(self, form) -> HttpResponse:
        form.instance.user = self.request.user
        form.instance.post = get_object_or_404(Post, pk=self.kwargs["pk"])
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse_lazy(
            "posts:post-detail", kwargs={"pk": self.kwargs["pk"]}
        )


class CommentaryDetailView(LoginRequiredMixin, generic.DetailView):
    queryset = Commentary.objects.select_related(
        "post__dish__dish_type", "user"
    )
    context_object_name = "comment"


class CommentaryDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Commentary
    success_url = reverse_lazy("posts:post-list")

templates/blog/commentary_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete this commentary</h1>
  <p>Are you sure you want to delete the commentary: {{ commentary }}?</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete!" class="btn btn-danger">
  </form>
{% endblock %}

templates/blog/commentary_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Commentary</h1>
  <hr>
    <strong>User:</strong>
    {{ comment.user| default:"Unknown user"  }}
    <hr>
    <strong>Post:</strong>
    {{ comment.post }}
    <hr>
    <strong>Created:</strong>
    {{ comment.created_time }}
    <hr>
    <strong>Content:</strong>
    {{ comment.content }}
  {% if user == comment.user %}
    <a
      style="float: right"
      class="btn btn-danger text-white"
      href="{% url 'posts:commentary-delete' pk=comment.pk %}"
    >
      Delete comment
    </a>
    <hr>
  {% endif %}
{% endblock%}

templates/blog/commentary_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} comment</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-outline-success">
  </form>
{% endblock %}

templates/blog/post_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete this post</h1>
  <p>Are you sure you want to delete the post: {{ post }}?</p>
  <p>All comments will be deleted</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete!" class="btn btn-danger">
  </form>
{% endblock %}

templates/blog/post_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="post-details">
    <h1>Post</h1>
    <hr>
    <div class="post-detail-item">
      <strong>Description:</strong>
      {{ post.description }}
    </div>
    <div class="post-detail-item">
      <strong>Rating:</strong>
      {{ post.rating }}
    </div>
    <div class="post-detail-item">
      <strong>Created:</strong>
      {{ post.created_time }}
    </div>
    <div class="post-detail-item">
      <strong>Dish:</strong>
      {{ post.dish }}
    </div>
    <div class="post-detail-item">
      <strong>User:</strong>
      {{ post.user|default:"Unknown user" }}
    </div>
    <hr>
    <a
      class="btn btn-success text-white"
      href="{% url 'posts:comment-create' pk=post.pk %}">
        Create comment
    </a>
    {% if post.commentaries.all %}
      <hr>
      <strong>Comments:</strong>
      <ul class="comment-list">
        {% for comment in post.commentaries.all %}
          <li class="comment-item">
            <a
              class="btn btn-secondary text-white"
              href="{% url 'posts:commentary-detail' pk=comment.pk %}">
              {{ comment.content }}
            </a>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p class="no-comments">There are no comments yet! You can add some one.</p>
    {% endif %}
    {% if user == post.user %}
      <hr>
      <a
        href="{% url 'posts:post-update' pk=post.pk %}"
        class="btn btn-info text-white"
      >
        Update post
      </a>
      <a
        style="float: right"
        class="btn btn-danger text-white"
        href="{% url 'posts:post-delete' pk=post.pk %}"
      >
        Delete post
      </a>
    {% endif %}
  </div>
{% endblock %}

templates/blog/post_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} post</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-outline-success">
  </form>
{% endblock %}

templates/blog/post_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Posts</h1>
  <div class="post-list">
    {% if post_list %}
      <ul class="list-group">
        {% for post in post_list %}
          <li class="list-group-item">
            <a href="{% url 'posts:post-detail' post.pk %}" class="post-title">
              {{ post.description|truncatewords:2 }}
            </a>
            <div class="post-info">
              <span class="post-rating">Rating: {{ post.rating }}</span>
              <span class="post-created-time">Created time: {{ post.created_time }}</span>
              {% if post.user %}
                <span class="post-user">User: {{ post.user.username }}</span>
              {% else %}
                <span class="post-user">Unknown user</span>
              {% endif %}
              <span class="post-dish">Dish: {{ post.dish }}</span>
            </div>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p class="no-posts">There are no posts yet</p>
    {% endif %}
  </div>
{% endblock %}