blob/urls.py
from django.urls import path

from blob.views import (
    PostListView,
    PostUpdateView,
    PostDetailView,
    PostDeleteView,
    CommentaryCreateView,
    CommentaryDetailView,
    CommentaryDeleteView,
)

urlpatterns = [
    path("", PostListView.as_view(), name="post-list"),
    path("<int:pk>/", PostDetailView.as_view(), name="post-detail"),
    path("<int:pk>/update/", PostUpdateView.as_view(), name="post-update"),
    path("<int:pk>/delete/", PostDeleteView.as_view(), name="post-delete"),
    path(
        "<int:pk>/commentaries/create/",
        CommentaryCreateView.as_view(),
        name="comment-create",
    ),
    path(
        "commentaries/<int:pk>/",
        CommentaryDetailView.as_view(),
        name="commentary-detail",
    ),
    path(
        "commentaries/<int:pk>/delete/",
        CommentaryDeleteView.as_view(),
        name="commentary-delete",
    ),
]

app_name = "posts"

dishes/urls.py
from django.urls import path

from blog.views import PostCreateView
from dishes.views import (
    DishCreateView,
    DishDeleteView,
    DishDetailView,
    DishListView,
    DishTypeCreateView,
    DishTypeDeleteView,
    DishTypeDetailView,
    DishTypeListView,
    DishTypeUpdateView,
    DishUpdateView,
    IndexView,
    UpdateLikeView,
    basket_add,
    basket_remove,
)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path(
        "dishes/<int:pk>/like/",
        UpdateLikeView.as_view(),
        name="update_like_dish",
    ),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path(
        "dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"
    ),
    path(
        "dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"
    ),
    path(
        "dishes/<int:pk>/create_post/",
        PostCreateView.as_view(),
        name="post-create",
    ),
    path("types/", DishTypeListView.as_view(), name="dish_type-list"),
    path(
        "types/<int:pk>/",
        DishTypeDetailView.as_view(),
        name="dish_type-detail",
    ),
    path(
        "types/create/", DishTypeCreateView.as_view(), name="dish_type-create"
    ),
    path(
        "types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish_type-update",
    ),
    path(
        "types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish_type-delete",
    ),
    path("baskets/add/<int:dish_id>/", basket_add, name="basket-add"),
    path(
        "baskets/remove/<int:basket_id>/", basket_remove, name="basket-remove"
    ),
]

app_name = "cuisine"

online_restaurant/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from orders.views import stripe_webhook_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("dishes.urls", namespace="cuisine")),
    path("accounts/", include("allauth.urls")),
    path("users/", include("users.urls", namespace="users")),
    path("posts/", include("blog.urls", namespace="posts")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("webhook/stripe/", stripe_webhook_view, name="stripe-webhook"),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path

from orders.views import (
    CanceledTemplateView,
    OrderCreateView,
    OrderDetailView,
    OrderListView,
    SuccessTemplateView,
)

urlpatterns = [
    path("create/", OrderCreateView.as_view(), name="order-create"),
    path("", OrderListView.as_view(), name="order-list"),
    path("<int:pk>/", OrderDetailView.as_view(), name="order-detail"),
    path(
        "order-success/", SuccessTemplateView.as_view(), name="order-success"
    ),
    path(
        "order-canceled/",
        CanceledTemplateView.as_view(),
        name="order-canceled",
    ),
]

app_name = "orders"

dishes/models.py
from __future__ import annotations

import os
import uuid

import stripe
from _decimal import Decimal
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import F, Sum
from django.urls import reverse

stripe.api_key = settings.STRIPE_SECRET_KEY


class DishType(models.Model):
    name = models.CharField(max_length=63, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name


def dish_image_file_path(instance: Dish, filename: str) -> str:
    _, extension = os.path.splitext(filename)
    from django.utils.text import slugify

    filename = f"{slugify(instance.name)}-{uuid.uuid4()}{extension}"
    return os.path.join("uploads/dishes/", filename)


class Dish(models.Model):
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField()
    price = models.DecimalField(
        max_digits=7,
        decimal_places=2,
        validators=[MinValueValidator(limit_value=0)],
    )
    image = models.ImageField(null=False, upload_to=dish_image_file_path)
    stripe_product_price_id = models.CharField(
        max_length=128, null=True, blank=True
    )
    dish_type = models.ForeignKey(
        DishType, on_delete=models.CASCADE, related_name="dishes"
    )
    likes = models.ManyToManyField(
        get_user_model(), related_name="dishes", blank=True
    )

    class Meta:
        verbose_name_plural = "dishes"
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self) -> str:
        return reverse("cuisine:dish-detail", kwargs={"pk": self.pk})

    def save(
        self,
        force_insert: bool = False,
        force_update: bool = False,
        using: str = None,
        update_fields: list = None,
    ) -> None:
        if not self.stripe_product_price_id:
            stripe_product_price = self.create_stripe_product_price()
            self.stripe_product_price_id = stripe_product_price["id"]
        super().save(
            force_insert=False,
            force_update=False,
            using=None,
            update_fields=None,
        )

    def create_stripe_product_price(self) -> stripe.Price:
        stripe_product = stripe.Product.create(name=self.name)
        stripe_product_price = stripe.Price.create(
            product=stripe_product["id"],
            unit_amount=round(self.price * 100),
            currency="usd",
        )
        return stripe_product_price


class BasketQuerySet(models.QuerySet):
    def total_sum(self) -> Decimal:
        result = self.aggregate(
            total_sum=Sum(
                F("dish__price") * F("quantity"),
                output_field=models.DecimalField(
                    max_digits=15, decimal_places=2
                ),
            )
        )
        return result["total_sum"]

    def total_quantity(self) -> int:
        result = self.aggregate(total_quantity=Sum("quantity"))
        return result["total_quantity"]

    def stripe_products(self) -> list:
        line_items = []
        for basket in self:
            item = {
                "price": basket.dish.stripe_product_price_id,
                "quantity": basket.quantity,
            }
            line_items.append(item)
        return line_items


class Basket(models.Model):
    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="baskets"
    )
    dish = models.ForeignKey(
        Dish, on_delete=models.CASCADE, related_name="baskets"
    )
    quantity = models.PositiveSmallIntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)

    objects = BasketQuerySet.as_manager()

    def __str__(self) -> str:
        return f"Basket for user {self.user} | Dish: {self.dish}"

    @property
    def sum(self) -> Decimal:
        return self.dish.price * self.quantity

    def de_json(self) -> dict:
        basket_item = {
            "dish_name": self.dish.name,
            "quantity": self.quantity,
            "price": float(self.dish.price),
            "sum": float(self.sum),
        }
        return basket_item

dishes/forms.py
from django import forms

from dishes.models import Dish, DishType


class NameSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
    )


class DishCustomizeForm(forms.ModelForm):
    dish_type = forms.ModelChoiceField(
        queryset=DishType.objects.all(), widget=forms.RadioSelect
    )

    class Meta:
        model = Dish
        fields = ("name", "description", "price", "image", "dish_type")

dishes/views.py
import os

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic

from dishes.forms import DishCustomizeForm, NameSearchForm
from dishes.models import Basket, Dish, DishType


def is_admin(user) -> bool:
    return user.is_authenticated and user.is_staff


decorators = [login_required, user_passes_test(is_admin)]


class IndexView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dishes/index.html"

    def get_context_data(self, **kwargs: dict) -> dict:
        context = super().get_context_data(**kwargs)
        self.request.session["num_visits"] = (
            self.request.session.get("num_visits", 0) + 1
        )
        context["num_visits"] = self.request.session.get("num_visits", 1)
        context["count_dishes"] = Dish.objects.count()
        context["count_dish_types"] = DishType.objects.count()
        context["contact"] = os.getenv("CONTACT")

        return context


class DishListView(LoginRequiredMixin, generic.ListView):
    template_name = "dishes/dishes_list.html"
    paginate_by = 5

    def get_context_data(
        self, *, object_list: list = None, **kwargs: dict
    ) -> dict:
        context = super().get_context_data()
        name = self.request.GET.get("name", "")
        context["search_form"] = NameSearchForm(initial={"name": name})

        return context

    def get_queryset(self) -> QuerySet:
        form = NameSearchForm(self.request.GET)
        queryset = Dish.objects.select_related("dish_type")

        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])

        return queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    queryset = Dish.objects.prefetch_related(
        "posts__commentaries", "likes"
    ).select_related("dish_type")


@method_decorator(decorators, name="dispatch")
class DishCreateView(generic.CreateView):
    model = Dish
    form_class = DishCustomizeForm
    success_url = reverse_lazy("cuisine:dish-list")


@method_decorator(decorators, name="dispatch")
class DishUpdateView(generic.UpdateView):
    model = Dish
    form_class = DishCustomizeForm
    success_url = reverse_lazy("cuisine:dish-list")


@method_decorator(decorators, name="dispatch")
class DishDeleteView(generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("cuisine:dish-list")


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    context_object_name = "dish_type_list"
    template_name = "dishes/dish_types_list.html"
    paginate_by = 5


class DishTypeDetailView(LoginRequiredMixin, generic.DetailView):
    model = DishType
    template_name = "dishes/dish_type_detail.html"


@method_decorator(decorators, name="dispatch")
class DishTypeCreateView(generic.CreateView):
    model = DishType
    fields = "__all__"
    template_name = "dishes/dish_type_form.html"
    success_url = reverse_lazy("cuisine:dish_type-list")


@method_decorator(decorators, name="dispatch")
class DishTypeUpdateView(generic.UpdateView):
    model = DishType
    fields = "__all__"
    template_name = "dishes/dish_type_form.html"
    success_url = reverse_lazy("cuisine:dish_type-list")


@method_decorator(decorators, name="dispatch")
class DishTypeDeleteView(generic.DeleteView):
    model = DishType
    template_name = "dishes/dish_type_confirm_delete.html"
    success_url = reverse_lazy("cuisine:dish_type-list")


class UpdateLikeView(generic.DetailView):
    model = Dish
    fields = "__all__"

    def get(
        self, request: HttpRequest, *args: tuple, **kwargs: dict
    ) -> HttpResponseRedirect:
        dish = get_object_or_404(Dish, pk=self.kwargs["pk"])
        user = get_object_or_404(get_user_model(), pk=self.request.user.pk)
        if user not in dish.likes.all():
            dish.likes.add(user)
        else:
            dish.likes.remove(user)
        return HttpResponseRedirect(
            reverse("cuisine:dish-detail", kwargs={"pk": self.kwargs["pk"]})
        )


@login_required
def basket_add(request: HttpRequest, dish_id: int) -> HttpResponseRedirect:
    dish = get_object_or_404(Dish, pk=dish_id)
    baskets = Basket.objects.filter(user=request.user, dish=dish)

    if not baskets.exists():
        Basket.objects.create(user=request.user, dish=dish, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()

    return HttpResponseRedirect(request.META["HTTP_REFERER"])


@login_required
def basket_remove(
    request: HttpRequest, basket_id: int
) -> HttpResponseRedirect:
    basket = get_object_or_404(Basket, id=basket_id)
    basket.delete()

    return HttpResponseRedirect(request.META["HTTP_REFERER"])

templates/dishes/baskets.html
{% if baskets %}
    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
        Basket <span class="badge-secondary badge-pill">{{ baskets.total_quantity }} </span>
    </h4>
    {% for basket in baskets %}
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">{{ basket.dish.name }}</h5>
                <p class="card-text">{{ basket.dish.description }}</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item bg-light">
                    <div class="row text-center">
                        <div class="col-lg-4">
                            <input name="basketID" type="number" class="form-control"
                                   value="{{ basket.quantity }}" min="0">
                        </div>
                        <div class="col-lg-4">{{ basket.sum|floatformat:2 }} usd.</div>
                        <div class="col-lg-4">
                            <a href="{% url 'cuisine:basket-remove' basket.id %}">
                                <i class="fas fa-trash"></i>
                            </a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    {% endfor %}
    <div class="card mb-3">
        <div class="card-footer">
            <p class="float-left">All</p>
            <h4 class="float-right">{{ baskets.total_sum|floatformat:2  }} usd.</h4>
        </div>
    </div>
    <a class="btn btn-success btn-lg float-right" href="{% url 'orders:order-create' %}">
        Make an order
    </a>
{% else %}
    <h4 class="mt-3 mb-3 text-center">
        Empty basket
    </h4>
{% endif %}

templates/dishes/dish-detail.html
{% extends "base.html" %}

{% block content %}
  <h1 >Name: {{ dish.name }}</h1>
    <strong>Description:</strong>
    {{ dish.description }}
    <hr>
    <strong>Price:</strong>
    {{ dish.price }}
    <hr>
    <strong>Image:</strong>
    <img src="{{ dish.image.url|safe }}" alt="Image" height="400">
    <hr>
    <strong>Type:</strong>
    {{ dish.dish_type }}
    <hr>
      <a
        href="{% url 'posts:post-create'%}"
        class="btn btn-dark text-white"
      >
        Create post
      </a>
    {% if dish.posts.all %}
      <hr>
    <strong>Posts:</strong>

      {% for post in dish.posts.all %}
        <div>
        <a
        style="float: right"
        class="btn btn-secondary text-white"
        href="{% url 'posts:post-detail' pk=post.pk %}">
          {{ post }}
        </a>
        </div>
      {% endfor %}
    {% endif %}
    <hr>
    <strong>Likes:</strong>
    {{ dish.likes.count }}
    {% if user.is_authenticated %}
      {% if user in dish.likes.all %}
        <form method="get" action="{% url 'cuisine:update_like_dish' pk=dish.pk %}">
          {% csrf_token %}
          <button type="submit">Unlike</button>
        </form>
      {% else %}
        <form method="get" action="{% url 'cuisine:update_like_dish' pk=dish.pk %}">
          {% csrf_token %}
          <button type="submit">Like</button>
        </form>
      {% endif %}
    {% endif %}
    {% if user.is_staff %}
      <hr>
      <a
        href="{% url 'cuisine:dish-update' pk=dish.pk %}"
        class="btn btn-dark link-to-page text-white"
      >
        Update dish
      </a>
    <a
      style="float: right"
      class="btn btn-secondary text-white"
      href="{% url 'cuisine:dish-delete' pk=dish.pk %}">Delete
    </a>
    <hr>
  {% endif %}
{% endblock%}

templates/dishes/dish_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete this dish</h1>
  <p>Are you sure you want to delete the dish: {{ dish }}?</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete!" class="btn btn-danger">
  </form>
{% endblock %}

templates/dishes/dish_detail.html
{% extends "base.html" %}

{% block content %}
  <h1 >Name: {{ dish.name }}</h1>
    <strong>Description:</strong>
    {{ dish.description }}
    <hr>
    <strong>Price:</strong>
    {{ dish.price }}
    <hr>
    <strong>Image:</strong>
    <img src="{{ dish.image.url|safe }}" alt="Image" height="400">
    <hr>
    <strong>Type:</strong>
    {{ dish.dish_type }}
      <a
        style="float: right"
        href="{% url 'cuisine:post-create' pk=dish.pk %}"
        class="btn text-bg-success"
      >
        Create post
      </a>
    {% if dish.posts.all %}
      <hr>
    <strong class="text-bg-success">Posts:</strong>
      <ul>
      {% for post in dish.posts.all %}
        <br>
        <li>
        <a
        class="btn btn-secondary text-white"
        href="{% url 'posts:post-detail' pk=post.pk %}">
          {{ post }}
        </a>
          <br>
        <br>
        </li>
      {% endfor %}
      </ul>
    {% endif %}
    <hr>
    <strong class="text-bg-warning">Likes:</strong>
    {{ dish.likes.count }}
    {% if user.is_authenticated %}
      {% if user in dish.likes.all %}
        <form method="get" action="{% url 'cuisine:update_like_dish' pk=dish.pk %}">
          {% csrf_token %}
            <div class="d-flex justify-content-end">
            <button
                type="submit"
                class="btn btn-outline-success text-bg-warning"
            >
              Unlike
            </button>
            </div>
        </form>
      {% else %}
        <form method="get" action="{% url 'cuisine:update_like_dish' pk=dish.pk %}">
          {% csrf_token %}
            <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-outline-success text-bg-warning">Like</button>
            </div>
        </form>
      {% endif %}
    {% endif %}
    {% if user.is_staff %}
      <hr>
      <a
        href="{% url 'cuisine:dish-update' pk=dish.pk %}"
        class="btn btn-info link-to-page text-white"
      >
        Update dish
      </a>
    <a
      style="float: right"
      class="btn btn-danger text-white"
      href="{% url 'cuisine:dish-delete' pk=dish.pk %}"
    >
      Delete
    </a>
  {% endif %}
  <hr>
{% endblock%}

templates/dishes/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish</h1>
  <form action="" method="post" novalidate enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-outline-success">
  </form>
{% endblock %}

templates/dishes/dish_type-detail.html
{% extends "base.html" %}

{% block content %}
  <h1 >Name: {{ dishtype.name }}</h1>
  {% if user.is_staff %}
    <hr>
    <a
      href="{% url 'cuisine:dish_type-update' pk=dishtype.pk %}"
      class="btn btn-dark link-to-page text-white"
    >
      Update type of dish
    </a>
    <a
      style="float: right"
      class="btn btn-secondary text-white"
      href="{% url 'cuisine:dish_type-delete' pk=dishtype.pk %}">Delete
    </a>
    <hr>
  {% endif %}
{% endblock%}

templates/dishes/dish_type_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete this dish</h1>
  <p>Are you sure you want to delete the type of dish: {{ dishtype }}?</p>
    <p><i>All dishes with this type will be also deleted!</i></p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete!" class="btn btn-danger">
  </form>
{% endblock %}

templates/dishes/dish_type_detail.html
{% extends "base.html" %}

{% block content %}
  <h1 >Name: {{ dishtype.name }}</h1>
  {% if user.is_staff %}
    <hr>
    <a
      href="{% url 'cuisine:dish_type-update' pk=dishtype.pk %}"
      class="btn btn-info text-white"
    >
      Update type of dish
    </a>
    <a
      style="float: right"
      class="btn btn-danger text-white"
      href="{% url 'cuisine:dish_type-delete' pk=dishtype.pk %}">Delete
    </a>
    <hr>
  {% endif %}
{% endblock%}

templates/dishes/dish_type_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish_type</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-outline-success">
  </form>
{% endblock %}

templates/dishes/dish_types-list.html
{% extends "base.html" %}

{% block content %}
  <h1>Types of dishes</h1>
  <hr>
  {% if user.is_staff %}
    <a
      style="float: right"
      class="btn btn-secondary text-white"
      href="{% url 'cuisine:dish_type-create' %}">Create
    </a>
  {% endif %}
  {% if dish_type_list %}
    <ul>
      {% for type in dish_type_list %}
        {% if user.is_staff %}
          <li>
            <a href="{% url 'cuisine:dish_type-detail' pk=type.pk %}">
              {{ type.name|capfirst }}
            </a>
            <hr>
          </li>
        {% else %}
          <li>
            Name: {{ type.name|capfirst }}
          </li>
        {% endif %}
      {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

templates/dishes/dish_types_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Types of dishes</h1>
  <hr>
  {% if user.is_staff %}
    <a
      style="float: right"
      class="btn btn-light text-bg-warning"
      href="{% url 'cuisine:dish_type-create' %}"
    >
      Create
    </a>
  {% endif %}
  {% if dish_type_list %}
    <ul>
      {% for type in dish_type_list %}
        {% if user.is_staff %}
          <li>
            <a href="{% url 'cuisine:dish_type-detail' pk=type.pk %}">
              {{ type.name|capfirst }}
            </a>
            <hr>
          </li>
        {% else %}
          <li>
            Name: {{ type.name|capfirst }}
          </li>
        {% endif %}
      {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

templates/dishes/dishes_list.html
{% extends "base.html" %}
{% load cache %}

{% block content %}
  <h1>Dishes:</h1>
  <hr>
  <form action="" method="get" class="form-inline">
    {{ search_form }}
    <input class="btn btn-outline-light" type="submit" value="🔎">
  </form>
  {% if user.is_staff %}
    <br>
    <a
        class="btn btn-light text-bg-warning text-lg-end"
        href="{% url 'cuisine:dish-create' %}">Create
    </a>
    <div></div>

  {% endif %}
  <hr>

  {% cache 30 object_list %}
  {% if dish_list %}

    <ul>
      {% for dish in dish_list %}
        <li class="border bg-light p-3 mb-3 dish-card">
          <div class="dish-details">
            <a href="{{ dish.get_absolute_url }}">{{ dish.name }}</a>
            <br>
            Description: {{ dish.description }}
            <br>
            Price: {{ dish.price }}
            <br>
            Type of dish: {{ dish.dish_type }}
          </div>
          <div class="actions">
            <a class="btn btn-success"
               href="{% url 'cuisine:basket-add' dish.id %}">
              Add to basket
            </a>
          </div>

        </li>

      {% endfor %}
    </ul>
  {% else %}
    <h2>There are no dishes yet</h2>
    <br>
  {% endif %}
  {% endcache %}
{% endblock %}

templates/dishes/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Welcome</h1>
  <hr>
{% with count=count_dishes %}
  <h4>There {{ count }} dish{{ count|pluralize:",es" }}.</h4>
  <hr>
{% endwith %}
  {% with count=count_dish_types %}
  <h4>There {{ count }} dish type{{ count|pluralize}}.</h4>
  <hr>
{% endwith %}
  <div style="height: 600px"></div>
  You can contact the owner by phone: {{ contact }}
  <hr>
  <p>You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}</p>
{% endblock %}