blob/urls.py
from django.urls import path

from blob.views import (
    PostListView,
    PostUpdateView,
    PostDetailView,
    PostDeleteView,
    CommentaryCreateView,
    CommentaryDetailView,
    CommentaryDeleteView,
)

urlpatterns = [
    path("", PostListView.as_view(), name="post-list"),
    path("<int:pk>/", PostDetailView.as_view(), name="post-detail"),
    path("<int:pk>/update/", PostUpdateView.as_view(), name="post-update"),
    path("<int:pk>/delete/", PostDeleteView.as_view(), name="post-delete"),
    path(
        "<int:pk>/commentaries/create/",
        CommentaryCreateView.as_view(),
        name="comment-create",
    ),
    path(
        "commentaries/<int:pk>/",
        CommentaryDetailView.as_view(),
        name="commentary-detail",
    ),
    path(
        "commentaries/<int:pk>/delete/",
        CommentaryDeleteView.as_view(),
        name="commentary-delete",
    ),
]

app_name = "posts"

online_restaurant/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from orders.views import stripe_webhook_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("dishes.urls", namespace="cuisine")),
    path("accounts/", include("allauth.urls")),
    path("users/", include("users.urls", namespace="users")),
    path("posts/", include("blog.urls", namespace="posts")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("webhook/stripe/", stripe_webhook_view, name="stripe-webhook"),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path

from orders.views import (
    CanceledTemplateView,
    OrderCreateView,
    OrderDetailView,
    OrderListView,
    SuccessTemplateView,
)

urlpatterns = [
    path("create/", OrderCreateView.as_view(), name="order-create"),
    path("", OrderListView.as_view(), name="order-list"),
    path("<int:pk>/", OrderDetailView.as_view(), name="order-detail"),
    path(
        "order-success/", SuccessTemplateView.as_view(), name="order-success"
    ),
    path(
        "order-canceled/",
        CanceledTemplateView.as_view(),
        name="order-canceled",
    ),
]

app_name = "orders"

orders/models.py
from django.contrib.auth import get_user_model
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

from dishes.models import Basket
from users.models import validate_ukrainian_phone_number


class Order(models.Model):
    STATUSES = (
        (0, "created"),
        (1, "paid"),
        (2, "on_way"),
        (3, "delivered"),
    )
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email = models.EmailField()
    phone = PhoneNumberField(
        region="UA",
        validators=[
            validate_ukrainian_phone_number,
        ],
    )
    address = models.CharField(max_length=256)
    basket_history = models.JSONField(default=dict)
    created = models.DateTimeField(auto_now_add=True)
    status = models.SmallIntegerField(default=0, choices=STATUSES)
    initiator = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="orders"
    )

    def __str__(self) -> str:
        return f"Order #{self.id}. {self.first_name} {self.last_name}"

    def update_after_payment(self) -> None:
        baskets = Basket.objects.filter(user=self.initiator)
        self.status = self.STATUSES[1][0]
        self.basket_history = {
            "purchased_items": [basket.de_json() for basket in baskets],
            "total_sum": float(baskets.total_sum()),
        }
        baskets.delete()
        self.save()

orders/forms.py
from django import forms
from phonenumber_field.formfields import PhoneNumberField

from orders.models import Order


class OrderForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(), required=True)
    last_name = forms.CharField(widget=forms.TextInput(), required=True)
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={"placeholder": "example@gmail.com"}),
        required=True,
    )
    phone = PhoneNumberField(
        region="UA",
        widget=forms.TextInput(attrs={"placeholder": "Enter phone number"}),
        required=True,
    )
    address = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Ukraine, Lviv, Franko, 78",
            }
        ),
        required=True,
    )

    class Meta:
        model = Order
        fields = ("first_name", "last_name", "email", "address", "phone")

orders/views.py
from http import HTTPStatus

import stripe
from django.conf import settings
from django.contrib.auth import get_user_model, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet
from django.http import (
    HttpRequest,
    HttpResponse,
    HttpResponseBadRequest,
    HttpResponseRedirect,
)
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView

from dishes.models import Basket
from orders.forms import OrderForm
from orders.models import Order

stripe.api_key = settings.STRIPE_SECRET_KEY


class SuccessTemplateView(TemplateView):
    template_name = "orders/success.html"

    def get(self, request, *args, **kwargs) -> HttpResponse:
        session_id = request.GET.get("session_id")

        if session_id:
            # Retrieve information from Stripe session metadata
            session = stripe.checkout.Session.retrieve(session_id)
            user_id = session.metadata.get("user_id")

            if user_id:
                try:
                    user = get_user_model().objects.get(id=user_id)
                    user.backend = (
                        "allauth.account.auth_backends.AuthenticationBackend"
                    )
                    login(request, user)
                except get_user_model().DoesNotExist:
                    return HttpResponseBadRequest(
                        "User does not exist", status=HTTPStatus.BAD_REQUEST
                    )
        return super().get(request, *args, **kwargs)


class CanceledTemplateView(LoginRequiredMixin, TemplateView):
    template_name = "orders/canceled.html"


class OrderListView(LoginRequiredMixin, generic.ListView):
    template_name = "orders/orders.html"
    ordering = ("-created",)

    def get_queryset(self) -> QuerySet:
        queryset = Order.objects.select_related("initiator")
        return queryset.filter(initiator=self.request.user)


class OrderDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "orders/order.html"
    model = Order


class OrderCreateView(LoginRequiredMixin, CreateView):
    template_name = "orders/order-create.html"
    form_class = OrderForm
    success_url = reverse_lazy("orders:order-create")

    def post(
        self, request: HttpRequest, *args: tuple, **kwargs: dict
    ) -> HttpResponseRedirect:
        form = self.get_form()
        if form.is_valid():
            super().post(request, *args, **kwargs)
            baskets = Basket.objects.filter(user=self.request.user)
            checkout_session = stripe.checkout.Session.create(
                line_items=baskets.stripe_products(),
                metadata={
                    "order_id": self.object.id,
                    "user_id": self.request.user.id,  # save user
                },
                customer_email=self.request.user.email,
                mode="payment",
                success_url="https://{}{}".format(
                    settings.DOMAIN_NAME, reverse("orders:order-success")
                )
                + "?session_id={CHECKOUT_SESSION_ID}",
                cancel_url="https://{}{}".format(
                    settings.DOMAIN_NAME, reverse("orders:order-canceled")
                ),
            )
            return HttpResponseRedirect(
                checkout_session.url, status=HTTPStatus.SEE_OTHER
            )
        else:
            return render(request, self.template_name, {"form": form})

    def get_initial(self) -> dict:
        initial = super().get_initial()
        user = self.request.user

        if user.is_authenticated:
            initial["first_name"] = user.first_name
            initial["last_name"] = user.last_name
            initial["email"] = user.email
            initial["phone"] = user.phone

        return initial

    def form_valid(self, form: OrderForm) -> HttpResponseRedirect:
        form.instance.initiator = self.request.user
        return super().form_valid(form)


@csrf_exempt
def stripe_webhook_view(request: HttpRequest) -> HttpResponse:
    payload = request.body
    sig_header = request.META["HTTP_STRIPE_SIGNATURE"]
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, settings.STRIPE_WEBHOOK_SECRET
        )
    except ValueError as e:
        print(e)
        return HttpResponse(status=HTTPStatus.BAD_REQUEST)
    except stripe.error.SignatureVerificationError as e:
        print(e)
        return HttpResponse(status=HTTPStatus.BAD_REQUEST)

    # Handle the checkout.session.completed event
    if event["type"] == "checkout.session.completed":
        session = event["data"]["object"]

        fulfill_order(session)

    # Passed signature verification
    return HttpResponse(status=200)


def fulfill_order(session) -> None:
    order_id = int(session.metadata.order_id)
    order = get_object_or_404(Order, id=order_id)
    order.update_after_payment()

templates/orders/canceled.html
<!DOCTYPE html>
<html>
<head>
  <title>Checkout canceled</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <section>
    <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
  </section>
</body>
</html>

templates/orders/order-create.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <section>
        <div class="alert alert-warning text-center" role="alert">
            Please fill out this form to contact the courier.
        </div>
        <div class="container">
            <div class="py-5 text-center">
                <h1>Placing an order</h1>
            </div>
            <div class="row g-5">
                <div class="col-md-5 col-lg-4 order-md-last">
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-primary">Basket</span>
                        <span class="badge badge-primary badge-pill text-white">{{ baskets.total_quantity }}</span>
                    </h4>
                    <ul class="list-group mb-3">
                        {% for basket in baskets %}
                            <li class="list-group-item d-flex justify-content-between lh-sm">
                                <div>
                                    <h6 class="my-0">{{ basket.product.name }}</h6>
                                    <small class="text-muted">{{ basket.quantity }} dishes.</small>
                                </div>
                                <span class="text-muted">{{ basket.sum|floatformat:2 }} UAN.</span>
                            </li>
                        {% endfor %}
                        <li class="list-group-item d-flex justify-content-between">
                            <span>Amount to be paid</span>
                            <strong>{{ baskets.total_sum|floatformat:2 }} usd.</strong>
                        </li>
                    </ul>
                </div>
                <div class="col-md-7 col-lg-8">
                    <h4 class="mb-3">Delivery address</h4>
                    <form action="{% url 'orders:order-create' %}" method="post" novalidate>
                        {% csrf_token %}
                        <div class="row g-3">
                            <div class="col-sm-6">
                                {{ form.first_name|as_crispy_field }}
                            </div>

                            <div class="col-sm-6">
                                {{ form.last_name|as_crispy_field }}
                            </div>

                            <div class="col-12 mt-3">
                                {{ form.phone|as_crispy_field }}
                            </div>

                            <div class="col-12 mt-3">
                                {{ form.email|as_crispy_field }}
                            </div>

                            <div class="col-12 mt-3">
                                {{ form.address|as_crispy_field }}
                            </div>

                        <hr class="my-4">

                        <button class="w-100 btn btn-primary btn-lg" type="submit">Continue</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/orders/order.html
{% extends "base.html" %}

{% block content %}
    <section>
        <div class="container pt-5">
            <div class="text-center mt-5">
                <h1>Order #{{ object.id }}</h1>
                <div class="orders mt-5">
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Price</th>
                            <th scope="col">Sum</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for purchased_item in object.basket_history.purchased_items %}
                            <tr>
                                <th scope="row">
                                    {{ purchased_item.dish_name }}
                                </th>
                                <td>{{ purchased_item.quantity }}</td>
                                <td>{{ purchased_item.price|floatformat:2 }} usd.</td>
                                <td>{{ purchased_item.sum|floatformat:2 }} usd.</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <p class="float-right h4 mt-3">Total {{ object.basket_history.total_sum|floatformat:2 }} usd.</p>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/orders/orders.html
{% extends "base.html" %}
{% load humanize %}

{% block content %}
    <section>
        <div class="container pt-5">
            <div class="text-center mt-5">
                <h1>Orders</h1>
                <div class="orders mt-5">
                    <table class="table">
                        <thead>
                        <tr class="table-light">
                            <th scope="col">#</th>
                            <th scope="col">Status</th>
                            <th scope="col">Created</th>
                            <th scope="col">Total</th>
                            <th scope="col">Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for order in object_list %}
                            <tr>
                                <th scope="row">{{ order.id }}</th>
                                <td>{{ order.get_status_display }}</td>
                                <td>{{ order.created|naturaltime }}</td>
                                <td>{{ order.basket_history.total_sum|floatformat:2 }} usd.</td>
                                <td>
                                    <a href="{% url 'orders:order-detail' pk=order.pk %}">View</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/orders/success.html
{% extends "base.html" %}

{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header">
                            <h3 class="text-center font-weight-light my-4">Thank you for the order!</h3>
                        </div>
                        <div class="card-body text-center">
                            <h4>
                                Your order has been successfully completed.
                            </h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}